# backend/docker-compose.yml

services:
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: noteflow
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  api:
    build: .
    restart: always
    ports:
      - "127.0.0.1:8081:8080"
    environment:
      DB_URL: "postgres://${DB_USER}:${DB_PASSWORD}@db:5432/noteflow?sslmode=disable"
      JWT_SECRET: "${JWT_SECRET}"
      S3_ENDPOINT: "s3.ru1.storage.beget.cloud"
      S3_ACCESS_KEY: "${S3_ACCESS_KEY}"
      S3_SECRET_KEY: "${S3_SECRET_KEY}"
      S3_BUCKET: "${S3_BUCKET}"
      S3_SECURE: "true"
    depends_on:
      - db

volumes:
  db_data: